### ISSUE TITLE
How do we Safari browser tests on multiple simulators?

### ISSUE THREAD

**Issue by yaphatak** [facebook/FBSimulatorControl#12]
Even though multiple simulators are launched, I see only one simulator's safari is detected with web inspector.

**Comment by lawrencelomax** [comment]
I've reproduced this locally and the short answer is I don't know!

Running Multiple Simulators on the same machine has always been officially unsupported, but does (mostly) work. A quick sampling of the linked libraries for `Safari.app` and Googling for articles about the remote debugging protocol for Safari don't come up with much. 

I assume there must be some service that Safari has to connect to in order to manage connections to Simulators & Devices, it's worth starting there and then finding out what makes the assumption that there can only be one Simulator running at once. I certainly know that this assumption isn't made as far as devices are concerned.

**Comment by yaphatak** [comment]
Thanks for quick reply @lawrencelomax

**Comment by lawrencelomax** [comment]
I'm going to close this out for now. For next steps I'd suggest:
1) File a Radar along the lines of "Support Inspecting more than 1 Simulator in Safari"
2) Poke around `Safari.app` to see how this remote debugger protocol works (or enlist the help of somebody who knows how to do this).

**Comment by yaphatak** [comment]
Thanks. done with rdar://22792345. What you guys use for safari browser testing @ FB?
