### ISSUE TITLE
FBFramebufferVideo: getSubtractiveDecodeDuration signalled err=-12633

### ISSUE THREAD

**Issue by robbertvanginkel** [facebook/FBSimulatorControl#209]
When I launch a simulator with the following options:
`        FBSimulatorLaunchOptions launchOptions =
            FBSimulatorLaunchOptionsEnableDirectLaunch |
            FBSimulatorLaunchOptionsRecordVideo |
            FBSimulatorLaunchOptionsShowDebugWindow;
`

It happens often that I get an error like the following:
```
[10:39:54.125] getSubtractiveDecodeDuration signalled err=-12633 (kFigFormatWriterError_InvalidTimestamp) (decode timestamp is less than previous sample's decode timestamp) at /SourceCache/CoreMedia/CoreMedia-1562.240/Prototypes/FormatHandlers/FigFormatWriter_QTMovie.c line 9867
[10:39:54.129] FigMediaProcessorGetSampleBufferProcessor signalled err=-12785 (kFigBaseObjectError_Invalidated) (FigMediaProcessor was invalidated) at /SourceCache/CoreMedia/CoreMedia-1562.240/Prototypes/MediaConverter/FigMediaProcessor.c line 787
[10:39:54.129] VTCompressionSessionGetPixelBufferPool signalled err=-12903 (kVTInvalidSessionErr) (Session was invalidated) at /SourceCache/CoreMedia_frameworks/CoreMedia-1562.240/Sources/VideoToolbox/VTCompressionSession.c line 2250
2016-02-15 10:39:54.130 swoctopus[54300:4456275] 1 Time 25.790000 | Count 901 Time 25.772000 | Count 900 1
[10:39:54.131] assetWriter_AddPixelBuffer signalled err=-12633 (storage->failureError) (AssetWriter has posted a failure notification) at /SourceCache/CoreMedia/CoreMedia-1562.240/Prototypes/MediaConverter/FigRemaker.c line 14257
```

Which makes the video file unusable. I've tried to set `static const CMTimeScale FBFramebufferTimescale = 1000;` to a lower value. This seems helps avoid the error, but also makes the code drop a significant amount of frames. 

Any idea how this could be prevented?

**Comment by lawrencelomax** [comment]
The stability of the the video recording does need some work. Ideally we could have the `movieFragmentInterval` set and use `AVFileTypeMPEG4` but I was having difficulty getting a monotonic timestamp to work. It looks to be related to Timescale and the rounding mode. There is a guard that will drop frames if the timestamps in ascending frames are equal or out-of-order. 

I think it's possible that this check isn't enough and the rounding modes mean that if the timestamps are to close that writing will fail. We should probably also have a monotonic time created when the frames come in, rather than on the `mediaQueue` so that the timestamps for each frame are as accurate as possible.

**Comment by lawrencelomax** [comment]
@robbertvanginkel Since #230 #229 #228 you should see increased reliability and performance in scaled and unscaled video recording. Let me know if you're still encountering issues.

**Comment by robbertvanginkel** [comment]
Great! I'll test it soon and hopefully close the task.

**Comment by robbertvanginkel** [comment]
Gave it a shot and initially it wasn't stable. Then I changed the following in `FBFramebufferVideo.m`:

```
diff --git a/FBSimulatorControl/Framebuffer/FBFramebufferVideo.m b/FBSimulatorControl/Framebuffer/FBFramebufferVideo.m
index dfdb64b..ada9113 100644
--- a/FBSimulatorControl/Framebuffer/FBFramebufferVideo.m
+++ b/FBSimulatorControl/Framebuffer/FBFramebufferVideo.m
@@ -29,7 +29,7 @@ typedef NS_ENUM(NSInteger, FBFramebufferVideoState) {

 static const OSType FBFramebufferPixelFormat = kCVPixelFormatType_32ARGB;
 // Timescale is in microseconds.
-static const CMTimeScale FBFramebufferVideoTimescale = 10E4;
+static const CMTimeScale FBFramebufferVideoTimescale = 600;
 static const CMTimeScale FBFramebufferVideoRoundingMode = kCMTimeRoundingMethod_RoundTowardZero;

 @interface FBFramebufferVideo ()
```

as the docs on CMTimeScale mention the following:
```
/*!
	@typedef	CMTimeScale
	@abstract	Denominator of rational CMTime.
	@discussion	Timescales must be positive.
				Note: kCMTimeMaxTimescale is NOT a good choice of timescale for movie files.  
				(Recommended timescales for movie files range from 600 to 90000.)
*/
```

That got me stable video recordings! (Well, after figuring out I still had to call `stopRecording` with the changed API).

Thanks for the effort for improving this! It'd be great if you could verify that this helps and merge it in, otherwise I'll create a pull request over the weekend if I figure out what a recommended timescale is.

**Comment by lawrencelomax** [comment]
Nice! This sounds promising. You may have seen that in #233 there's now a Config object that can be used to change these values without updating `FBSimulatorControl` itself, since there has been quite a bit of churn getting these values correct. I'd suggest making changes to the defaults there in any PR that you make.

**Comment by robbertvanginkel** [comment]
Tried it and it seems much more stable. Closing this one for now. Thanks!
