### ISSUE TITLE
How to install an app with fbsimctl?

### ISSUE THREAD

**Issue by jeffl3ung** [facebook/FBSimulatorControl#261]
I have already booted a simulator. Now to try to install my app with the command as follows:
fbsimctl install "7FBA26B0-222A-4F51-82AB-BBD6E5B324BC" --application "test.ipa"

but it does not work.  Could you tell me what is wrong with this command?

**Comment by lawrencelomax** [comment]
`fbsimctl install /path/to/test.app` should do what you want. You will likely need to extract the `ipa` since it is basically a zipped-up `.app` with some other metadata. You can search online for extracting an `ipa`.

You don't need to pass UDID, as the `install` command will always operated on booted simulators. In any case the UDID comes *before* the `install` command.

**Comment by jeffl3ung** [comment]
If I boot 2 simulators, how to decide which one should install without UDID

**Comment by lawrencelomax** [comment]
Like I said, it comes *before* the `install` command:

`fbsimctl 7FBA26B0-222A-4F51-82AB-BBD6E5B324BC install /path/to/test.app`

**Comment by jeffl3ung** [comment]
thx

**Comment by lawrencelomax** [comment]
Closing.

**Comment by jeffl3ung** [comment]
Installed successfully. But launch and crash immediately. Do you know why?

**Comment by sapieneptus** [comment]
@jeffl3ung Sounds like it's the wrong architecture. If you installed a `.app` that you pulled out of an `.ipa` file, it's probably an arm build and not an intel architecture (i.e. physical device only). You'll need a simulator-compatible binary.

To build a simulator binary from Xcode, `cd` into the dir with your xcode project and run 
```
xcodebuild -arch i386 -sdk iphonesimulator9.3 //or whatever version
```
This should produce a `.app` bundle that is compatible with your simulator.
