### ISSUE TITLE
Configuring ASL logging

### ISSUE THREAD

**Issue by jmoody** [facebook/FBSimulatorControl#268]
Is it possible to configure the ASL logging?

I would like to turn it off completely if possible.  

I will admit that I haven't done a deep investigation of this - I thought it would be worth asking in case there was an obvious answer.

Thanks for your efforts!

**Comment by lawrencelomax** [comment]
Are you talking about `fbsimctl` or direct use of the `FBSimulatorControl` framework? If it's the former, we could probably use a `--silent` flag in order to silence all logging. If it's the latter you should take a look at  [`FBControlCoreGlobalConfiguration` for enabling and disabling `stderr` and `debug` logging.](https://github.com/facebook/FBSimulatorControl/blob/master/FBControlCore/Utility/FBControlCoreGlobalConfiguration.m)

**Comment by jmoody** [comment]
Thanks for the fast response.

> FBControlCoreGlobalConfiguration for enabling and disabling stderr and debug logging.

Perfect.  Exactly what I was looking for.

We are using the `FBSimalatorControl` framework directly.

The problem we are having is that ASL logs resist redirection; you cannot use `>&` to redirect stdout and stderr to a file.

Thanks!

**Comment by lawrencelomax** [comment]
> The problem we are having is that ASL logs resist redirection; you cannot use >& to redirect stdout and stderr to a file.

You could also replace the implementation of `FBControlCoreLogger` with a logger that just does nothing, throws away it's input or otherwise doesn't write to `stderr`. 

If there's anything else you need, let us know 👍
