### ISSUE TITLE
fbsimctl: Support waitUntilAllTestRunnersHaveFinishedTestingWithTimeout

### ISSUE THREAD

**Issue by plu** [facebook/FBSimulatorControl#281]
It would be great to support executing tests on the command line and wait for them to finish. Example:

```
fbsimctl --simulators $UDID launch_xctest $APP/PlugIns/UnitTests.xctest com.ebaykleinanzeigen.ebc --wait-with-timeout 600
```

Another thing that would be nice is getting the test output in some sort of machine readable format (JSON?). So we can transform that in whatever we like (e.g. JUnit).

**Comment by lawrencelomax** [comment]
Yes! This is something that makes a lot of sense. It should be pretty easy to get this up and running. The APIs for waiting as you point out. It's just a case of parsing the arguments, writing a reporter, and passing this down into where the tests are launched.

This is a decent and fun task for anybody who wants to hack on `fbsimctl` 😄

**Comment by plu** [comment]
I see that `fbsimctl` can already produce JSON formatted output. I have the feeling that implementing a generic reporter would make more sense. Then anybody can use that JSON stream as an input and transform it to whatever they like, e.g. JUnit. What do you think?

Regarding wiring `waitUntilAllTestRunnersHaveFinishedTestingWithTimeout`: I assume I should extend `Action.LaunchXCTest` in some way so that I can pass in a timeout value, right?

**Comment by lawrencelomax** [comment]
> I see that fbsimctl can already produce JSON formatted output. I have the feeling that implementing a generic reporter would make more sense

Yes, there is a reporter that is used to report events in either a human readable or JSON format. I never really envisioned using it for reporting test results however, as the format of the reported output can be substantially different between `JUnit`, `RSpec`, whatever. I would have thought going directly to the target output would make it easier to integrate with other tools, rather than adding another translation layer.

I could see that you could use the current reporter as-is, by passing it to a concrete implementation of `FBTestManagerTestReporter` that takes the `fbsimctl` reporter could be a good way to get started. You could also put the reporter in `XCTestBootstrap` and then it can be used by other consumer libraries.

> Regarding wiring waitUntilAllTestRunnersHaveFinishedTestingWithTimeout: I assume I should extend Action.LaunchXCTest in some way so that I can pass in a timeout value, right?

Yep, you can just add another associated type to the enumeration. I'd consider making the timeout optional for the time being. There's plenty of examples for how to construct a flag like this in `CommandParsers` and `CommandParsersTests`.

**Comment by plu** [comment]
I've added support for passing in the timeout parameter via `--test-timeout`. If that looks good to you I'll open a pull request for that.

**Comment by plu** [comment]
Just to avoid confusion and I start working on something wrong: You'd like to have a reporter in `XCTestBootstrap` that understands how to generate `RSpec` output for example. And in `fbsimctl` I can tell via some `enum` hooked into a `CommandParser` that I want to use that reporter? E.g. `--reporter-format rspec`
For the `JUnit` case we probably also want to specify via some command line argument where to write the `XML` to.

**Comment by anshu10165** [comment]
I have a scheme with set of UITests written using KIF, which can be run successfully using XCTool command line. Need some one help to run tests using fbsimctl , any help would be much appreciated here.
I am trying something command like:  fbsimctl simulator_UDID launch_xctest [path]/myTests.xctest    
[pathto]/com.myapp.app.

**Comment by plu** [comment]
Another thing I'm wondering regarding reporters: It would be great to support attaching multiple reporters, like it was possible with `xctool`

Example:

`fbsimctl launch_xctest --reporter rspec:'-' --reporter junit:'test-reports/junit.xml'`

Do you agree on this?

**Comment by lawrencelomax** [comment]
@plu I'll follow up with your questions as I see them, feel free to @ me if there's a specific answer you need.

> And in fbsimctl I can tell via some enum hooked into a CommandParser that I want to use that reporter? E.g. --reporter-format rspec

This sounds like a good approach. Allthough it may be more convenient to write the reporter in Swift, anyone who uses `XCTestBootstrap` will be able to use your reporter.

> For the JUnit case we probably also want to specify via some command line argument where to write the XML to.

This sounds like you may then want a `ReporterOutput` struct/enum in Swift for specifying the required parameters for each of the reporters, as the type of output in them will vary.

> Another thing I'm wondering regarding reporters: It would be great to support attaching multiple reporters, like it was possible with xctool

This is totally possible and should be quite trivial to implement, I wouldn't worry too much about what the CLI will look like for this first off, that can be refined later. You could have a `FBTestManagerTestReporterComposite` that would take an array of `FBTestManagerTestReporter`'s and report to each of them in sequence so that you can get multi-reporting.

**Comment by plu** [comment]
Thank you for your quick response! Everything sounds great to me. I'll have a look at implementing it soon and create a separate pull request for it.

**Comment by plu** [comment]
The easiest part is done. I hope I got the code style etc right.

**Comment by lawrencelomax** [comment]
> The easiest part is done. I hope I got the code style etc right

Yeah, it looks like what we have everywhere else

**Comment by plu** [comment]
We could close this issue. The topic of the issue has been solved and merged into `master` already. I hijacked the issue for more than one topic and will follow up with other pull requests on these topics. If you agree, let's close it.

**Comment by lawrencelomax** [comment]
Great, closing in favour of other issues/PRs
