### ISSUE TITLE
terminate and uninstall are very slow with fbsimctl

### ISSUE THREAD

**Issue by talkol** [facebook/FBSimulatorControl#289]
I'm using the command line fbsimctl and for some reason, the commands `terminate` and `uninstall` are very slow. They seem to do their job immediately, but the command line tool waits about 8-12 additional seconds (!) before finishing.

As a comparison, I used the original `xcrun simctl uninstall` and it works much faster and returns almost immediately.

The extra delay is a killer in e2e tests, is it possible to make these commands faster?

**Comment by lawrencelomax** [comment]
I don't doubt that there are some performance issues with linear scaling of some activities, such as fetching the list of simulators and finding the process ids of the running ones. This can make a bunch of syscalls, so will slow down with the more Simulators that you have in a set. I'd try out using a custom Simulator Set, with the `--set` argument and see if things get faster there.

`FBSimulatorControl` also has a bunch of additional remediations for failure scenarios (with timeouts). It could be that these are also adding a bunch of overhead. The best way to figure out what is slow in the running of the `fbsimctl` process is by getting time samples of the stack frames in order to determine which functions are slow/heavy:

You can collect a sample of the running process using `sample(1)`:
```bash
fbsimctl YOUR-COMMAND-HERE & sample $!
```

For example, this will collect the sample for `list`:
```bash
fbsimctl list & sample $!
```

You can also use `iprofiler(1)` to collect a sample, that can then be opened in `Instruments.app`:
```bash
# Note that you must provide the full path to the fbsimctl executable, you can't just have it in your $PATH
iprofiler -counters /usr/local/bin/fbsimctl list
```

I can see that `-[FBSimulatorSet allSimulators]` in particular is a heavy method  as it makes a bunch of syscalls to interrogate the process table. You might see some heavy traces for other methods in your command.

**Comment by EtgarSH** [comment]
@lawrencelomax: I've done some debug logging as you recommended in order to understand where's the slow point. Here are the results:

`# ./fbsimctl launch com.apple.mobilesafari`
> launching safari in the currently booted simulator

`# ./fbsimctl --debug-logging terminate com.apple.mobilesafari`
> terminating safari - this is the unusually slow command we want to investigate

#### `terminate` command debug-log with timestamps:

```
02:08:41 - CoreSimulator: Loading from /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework
02:08:41 - CoreSimulator: Successfully loaded
02:08:41 - CoreSimulator: SimDevice has correct path of /Applications/Xcode.app
02:08:41 - SimulatorKit: Loading from /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/SimulatorKit.framework
02:08:41 - SimulatorKit: Successfully loaded
02:08:41 - SimulatorKit: SimDeviceFramebufferService has correct path of /Applications/Xcode.app
02:08:41 - Loaded All Private Frameworks [CoreSimulator, SimulatorKit]
02:08:41 - Completed Pool Preconditons
02:08:41 - MobileDevice: Loading from /System/Library/PrivateFrameworks/MobileDevice.framework
02:08:41 - MobileDevice: Successfully loaded
02:08:41 - Loaded All Private Frameworks [MobileDevice]
02:08:41 - Killing Process MobileSafari | PID 5552
02:08:41 - Waiting on Process MobileSafari | PID 5552 to dissappear from the process table
02:08:41 - Killed Process MobileSafari | PID 5552
02:08:41 - Waiting for Process MobileSafari | PID 5552 to be removed from launchctl
02:08:51 - Process MobileSafari | PID 5552 has been removed from launchctl
02:08:51 - Quitting...
```

As you can see, the entire duration of the `terminate` command is 10 seconds, which is a big problem for us since we want to do it between e2e tests.

It seems that there's no problem with fetching the list of simulators or processes. The slowness originates from the explicit `Wait` at the end. Is this wait mandatory, can we somehow avoid it to speed up our tests by a factor of 10?

**Comment by lawrencelomax** [comment]
> It seems that there's no problem with fetching the list of simulators or processes. The slowness originates from the explicit Wait at the end. Is this wait mandatory, can we somehow avoid it to speed up our tests by a factor of 10?

We can certainly make this step optional, [but it exists for a good reason](https://github.com/facebook/FBSimulatorControl/blob/bb33ddcf8fdab607139c12127e192b4ef624018d/FBSimulatorControl/Interactions/FBSimulatorInteraction%2BLifecycle.m#L105).

The `launchctl` running on the Simulator will take a while to figure out that the Application Process has died:
1) The Application launched and has PID 42
2) The Application Process is terminated in `FBProcessTerminationStrategy`
3) The `launchctl` is aware that the Application has died.

Bear in mind that it can take some time for `launchctl` to become aware of the death of the Application Process. If you 'launch' an Application when it is already active, this has the same effect as bringing the Application to the foreground, which is probably *not* what most people want when they re-launch an Application.

If you terminate an Application, you're probably doing it so you can re-launch it with a fresh process. This can lead to unexpected failures, since an Application can be 're-launched' with the same process. 

Now, it may be possible for us to speed this process up by finding a way of terminating the Application via `launchctl` itself. You may also be able to 'get away' with killing the process and hoping that enough time has elapsed before the next launch of your Application, so that it will start with a fresh process.

**Comment by lawrencelomax** [comment]
It looks like this may be possible with:

`launchctl stop "UIKitApplication:com.apple.mobilesafari[0xdeb0]`. This would require us to be able to get to the service name, but this should also be possible. It means we then wouldn't have to busyloop while we wait for `launchctl` to respond.

**Comment by EtgarSH** [comment]
Just for the sport, I took the code [you pointed to](https://github.com/facebook/FBSimulatorControl/blob/bb33ddcf8fdab607139c12127e192b4ef624018d/FBSimulatorControl/Interactions/FBSimulatorInteraction%2BLifecycle.m#L105) and remarked the entire wait to simulate making it optional like we've discussed:

```objc
//    [simulator.logger.debug logFormat:@"Waiting for %@ to be removed from launchctl", process.shortDescription];
//    BOOL isGoneFromLaunchCtl = [NSRunLoop.currentRunLoop spinRunLoopWithTimeout:FBControlCoreGlobalConfiguration.fastTimeout untilTrue:^ BOOL {
//      return ![simulator.launchctl processIsRunningOnSimulator:process error:nil];
//    }];
//    if (!isGoneFromLaunchCtl) {
//      return [[FBSimulatorError
//        describeFormat:@"Process %@ did not get removed from launchctl", process.shortDescription]
//        failBool:error];
//    }
```

Then, I ran the following shell script:

```shell
for i in `seq 1 10`;
do
  fbsimctl/./fbsimctl launch com.apple.mobilesafari
  fbsimctl/./fbsimctl terminate com.apple.mobilesafari
done
```

Indeed, performance is increased times 10 (it now takes less than a second to terminate).

I was mostly concerned about your background-foreground comment, since I do want to make sure the process starts fresh, so I looked in the log to see whether the PIDs change:

```
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Bridge: Framebuffer ((null)) | HID (null) | Simulator Bridge: Connected
03:16:02 - Connection Did Connect => Bridge: Framebuffer ((null)) | HID (null) | (null)
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Bridge: Framebuffer ((null)) | HID (null) | (null)
03:16:05 - Application Did Launch => Process MobileSafari | PID 8526
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Process MobileSafari | PID 8526
03:16:06 - Connection Did Connect => Bridge: Framebuffer ((null)) | HID (null) | (null)
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Bridge: Framebuffer ((null)) | HID (null) | (null)
03:16:06 - Application Did Launch => Process MobileSafari | PID 8537
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Process MobileSafari | PID 8537
03:16:07 - Connection Did Connect => Bridge: Framebuffer ((null)) | HID (null) | (null)
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Bridge: Framebuffer ((null)) | HID (null) | (null)
03:16:07 - Application Did Launch => Process MobileSafari | PID 8548
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Process MobileSafari | PID 8548
03:16:08 - Connection Did Connect => Bridge: Framebuffer ((null)) | HID (null) | (null)
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Bridge: Framebuffer ((null)) | HID (null) | (null)
03:16:08 - Application Did Launch => Process MobileSafari | PID 8559
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Process MobileSafari | PID 8559
03:16:09 - Connection Did Connect => Bridge: Framebuffer ((null)) | HID (null) | (null)
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Bridge: Framebuffer ((null)) | HID (null) | (null)
03:16:09 - Application Did Launch => Process MobileSafari | PID 8570
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Process MobileSafari | PID 8570
03:16:10 - Connection Did Connect => Bridge: Framebuffer ((null)) | HID (null) | (null)
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Bridge: Framebuffer ((null)) | HID (null) | (null)
03:16:10 - Application Did Launch => Process MobileSafari | PID 8581
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Process MobileSafari | PID 8581
03:16:11 - Connection Did Connect => Bridge: Framebuffer ((null)) | HID (null) | (null)
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Bridge: Framebuffer ((null)) | HID (null) | (null)
03:16:11 - Application Did Launch => Process MobileSafari | PID 8592
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Process MobileSafari | PID 8592
03:16:12 - Connection Did Connect => Bridge: Framebuffer ((null)) | HID (null) | (null)
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Bridge: Framebuffer ((null)) | HID (null) | (null)
03:16:12 - Application Did Launch => Process MobileSafari | PID 8603
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Process MobileSafari | PID 8603
03:16:13 - Connection Did Connect => Bridge: Framebuffer ((null)) | HID (null) | (null)
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Bridge: Framebuffer ((null)) | HID (null) | (null)
03:16:13 - Application Did Launch => Process MobileSafari | PID 8614
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Process MobileSafari | PID 8614
03:16:14 - Connection Did Connect => Bridge: Framebuffer ((null)) | HID (null) | (null)
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Bridge: Framebuffer ((null)) | HID (null) | (null)
03:16:14 - Application Did Launch => Process MobileSafari | PID 8625
0C95C88B-992A-4EFA-8C30-E433A7CF1D7C | iPhone 6 | Booted | iPhone 6 | iOS 9.3: launch: Process MobileSafari | PID 8625
```

As you can see, every PID is indeed different... so I assume the foreground-background problem isn't happening in this case.. and as you can see, it's very quick.

How else can I check whether making the wait optional has negative side effects?

**Comment by lawrencelomax** [comment]
> How else can I check whether making the wait optional has negative side effects

I have seen this in the past when running `relaunch` action, which launch *immediately* after killing the process. It's also possible that waiting on the pid to disappear from the process table is also adding a 'sufficient wait' so that `launchctl` is aware of it.

I think the best solution here is going to be replacing the process killing with a `launchctl stop` command. It's going to mean we don't need all these conservative wait loops and means we're talking *directly* with the process management of the Simulator, so it should also mean that the logging is much better. If you kill a process with a signal, it will have to be detected first. If you *tell* `launchctl` to kill the process, it should have better (and faster) results.

**Comment by lawrencelomax** [comment]
`-[FBSimulatorLaunchTests testRelaunchesSafariApplication]` and  `-[FBSimulatorLaunchTests testRelaunchesSampleApplication]` will do this too.

**Comment by lawrencelomax** [comment]
I've found issues with FBSimulatorLaunchControl, so I hope to fix that up shortly.

**Comment by talkol** [comment]
Thanks! your latest commit https://github.com/facebook/FBSimulatorControl/commit/fbc570a9d7ed2859224296cc3ff84e1c931fb23a indeed fixes the slowness in `terminate`.

We still experience slowness in `uninstall` (relative to `xcrun simctl uninstall `), it's about 2-4 seconds. We'll investigate the cause and follow up.

Thanks again!

**Comment by lawrencelomax** [comment]
> Thanks! your latest commit fbc570a indeed fixes the slowness in terminate.

I have another change coming that will terminate a process directly via the Simulator's `launchctl`. From running this manually, there might be another performance gain.

> We still experience slowness in uninstall (relative to xcrun simctl uninstall), it's about 2-4 seconds. We'll investigate the cause and follow up.

`uninstall` will first ensure that the Application is not running, so may have a similar issue to `terminate`. Again, be possible to do this via `launchctl`, so there are probably some perf gains there.

**Comment by talkol** [comment]
Awesome

FBSimulatorControl is really an amazing and important project
As more and more mobile developers turn to automation testing and continuous integration, FBSimulatorControl becomes a critical part of our workflow due to the impossible limitations of the stock simulator controller. Any second we shave off in runtime is duplicated in a thousand executions (ideally we execute our entire test suite on every push)

**Comment by lawrencelomax** [comment]
> Any second we shave off in runtime is duplicated in a thousand executions (ideally we execute our entire test suite on every push)

There are additional optimizations that you can make by using `fbsimctl` that can lead to big gains in runtime. A traditional testing workflow may look like the following:

1) Start the e2e test for an Application
2) A Simulator is booted to run the tests.
3) The Application is installed to run the tests.
4) A test is started, against the installed Application and Simulator.
5) Diagnostic information (video, syslogs, etc.) are stored somewhere so they can be viewed later, along with the outcome of the test.
6) The Simulator is 'cleaned' or shutdown, ready for the next test.

If you delegate the management of Simulators into a process that is independent of the scheduling of the Test Runner you can perform some of these steps independently of the tests running themselves and get results even faster. This means that 1, 2 and 6 can be removed from the critical path of test running.

**Comment by lawrencelomax** [comment]
@talkol [`ba56d001`](https://github.com/facebook/FBSimulatorControl/commit/ba56d00182960d1b8838ad695c7ccf5e099af61b), has change the `terminate` command to use `launchctl stop SERVICE-NAME`, which should be much faster. If you could confirm this works well for you that would be great. If you have performance issues elsewhere please open some more tasks.
