### ISSUE TITLE
simulator.interact doesnt seem to do anything?  (Help Wanted)

### ISSUE THREAD

**Issue by matthewc13** [facebook/FBSimulatorControl#316]
With a valid FBSimulator instance `simulator.interact` does not seem to do anything. 

I am looking to do something like the following:
` [[simulator.interact bootSimulator:[FBSimulatorLaunchConfiguration defaultConfiguration]] installApplication:appToInstall];`

However I am having no luck. 

I can boot the simulator if I use my own boot strategy. However I would like to chain these interactions and install the app post boot. 

Any help with this would be appreciated.

**Comment by matthewc13** [comment]
Also if there is a better forum to post these questions please let me know, as I might have a few as the week progresses

**Comment by lawrencelomax** [comment]
> With a valid FBSimulator instance simulator.interact does not seem to do anything.

This is because an `FBInteraction` object by itself is inert, you need to call `perform:` on it for it to actually do anything. The reason for this is that you can chain multiple interactions together and then call `perform:` at the end of the chain to run them.

I do hope to one day move to a more obvious and procedural API that will make this more obvious, you should be able to see in recent commits that this is slowly happening for a number of actions like installing an App.

> Also if there is a better forum to post these questions please let me know

This is the best place for raising questions.

I'm closing this for now based on the above advice, but if you're having any more issues with this please feel free to re-open or open another task.
