### ISSUE TITLE
[Documentation Reqest] Provide example test target that doesn't depend on an Application target

### ISSUE THREAD

**Issue by jpsim** [facebook/FBSimulatorControl#32]
The README states that it should be possible to create test targets that don't depend on Application targets.

> Test targets can be made that don't depend on any Application targets, or that launch multiple Application targets.

I'd love to make use of this, but there don't seem to be any examples demonstrating how to do this.

So I'm creating this issue to track providing an example configuration in FBSimulatorControl documentation. Alternatively, this could be provided as an integration test.

Thanks!

**Comment by lawrencelomax** [comment]
Have you taken a look at `FBSimulatorControlApplicationLaunchTests` and the Test Bundle bundle that contains it `FBSimulatorControlTests`? This test launches `MobileSafari` which is an App Bundle that comes pre-installed on the Simulator.

We could add and check-in a couple of dummy-apps. These would be Simulator .app Bundles that Integration tests can just launch to confirm that 3rd-party (and multiple 3rd-party) works as intended.

`FBSimulatorControlTests` only depend on `FBSimulatorControl.framework` and no Applications. The Test Bundle itself doesn't need "Bundle Loader" to be set, since the `XCTest` bundle just loads the `FBSimulatorControl.framework` directly (with all the associated `rpath` settings to link in the Private Frameworks).

I think the first step to documenting this would be a Podspec for the Framework: I'm pretty sure that the specification to link in (and bundle) the `.framework` would be identical for `XCTest` and Application targets.

**Comment by lawrencelomax** [comment]
There is an [Integration Test to show how this can work](https://github.com/facebook/FBSimulatorControl/blob/master/FBSimulatorControlTests/Tests/Integration/FBSimulatorTestInjectionTests.m#L42). I'll take a look at the documentation to see if it needs clarifying.
