### ISSUE TITLE
Recording via HTTP server is broken

### ISSUE THREAD

**Issue by bootstraponline** [facebook/FBSimulatorControl#328]
I'm trying to replicate this record command via the HTTP server.

> fbsimctl --debug-logging record start -- listen -- record stop 1>&2

First I start the server:

* `./fbsimctl --debug-logging listen --http 8090`

Then I post to `localhost:8090/record` with `{ "start": true }` using Postman.

The response is:

```ruby
{
  "status": "failure",
  "message": "Error Domain=com.facebook.FBSimulatorControl Code=0 \"Expected Simulator C745F21A-65CA-41B1-A8D5-0EB627BF4DB1 to be Booted, but it was 'Shutdown'\" UserInfo={NSLocalizedDescription=Expected Simulator C745F21A-65CA-41B1-A8D5-0EB627BF4DB1 to be Booted, but it was 'Shutdown'}",
  "events": [
    {
      "event_type": "started",
      "timestamp": 1478796183,
      "subject": false,
      "target": {
        "state": "Shutdown",
        "os": "iOS 10.1",
        "name": "iPad Retina",
        "udid": "C745F21A-65CA-41B1-A8D5-0EB627BF4DB1",
        "device-name": "iPad Retina"
      },
      "event_name": "record"
    }
  ]
}
```

**Comment by lawrencelomax** [comment]
@bootstraponline when sending a request to a server in this way, you are targeting *all simulators* in the device set that you are using. This means that all of the Simulators will attempt to start video recording. As soon as a non-booted simulator is encountered, the command will error and fail.

If you send a Post to `/SIMULATOR-UDID/record` then you can target a specific simulator. Place the UDID of the sim you want to work with in the request. You can also start a server, for a *specific* simulator so that it will only ever target that simulator.

**Comment by bootstraponline** [comment]
Thank you for explaining. `/SIMULATOR-UDID/record` works.
