### ISSUE TITLE
fbsimctl on device not launching runner

### ISSUE THREAD

**Issue by JonGabilondoAngulo** [facebook/FBSimulatorControl#344]
Hi, I'm trying to run a test on a iPhone 6 with 10.1, Xcode 8.1. No success. I've read all posts here but I did not find a solution.
I'm using the WebDriverAgent project and trying to launch the IntegrationApp. I manage to run the IntegrationApp and its IntegrationTests from Xcode. Therefore I do have the IntegrationApp and the IntegrationTest-Runner app with its corresponding .xctest in his Plugin folder.

From the information I gathered here this should work
**fbsimctl -state=booted f7ef872537597d1626df65185c6e4d9f95c4f546  launch_xctest /Users/me/Library/Developer/Xcode/DerivedData/WebDriverAgent-czmwtfxwwepoqhgdtpnbqpovpwgf/Build/Products/Debug-iphoneos/IntegrationTests-Runner.app/PlugIns/IntegrationTests.xctest  com.facebook.IntegrationApp  --port 8100 --listen**

But nothing is launched. The "ActionRunner" does not succeed to create any   SequenceRunner in ->    **let runner = SequenceRunner(runners: targets.map { .....**

Is **-state=booted** necessary/correct for devices ? 
Could be that I have to provide the .xctest path on the Device (how can I know the path)? 
Has anyone succeeded ?
thanks.

**Comment by kumariswarnim** [comment]
@JonGabilondoAngulo I too have the same issues and I am waiting for someone to help me to sort this.

**Comment by JonGabilondoAngulo** [comment]
Hi,
don't feel --state=booted fits to devices. I removed it and it advances in the right direction.
But it needs testHostPath here:
**switch (action) {
      case .launchXCTest(let configuration):
        do {
          let strategy = FBDeviceTestRunStrategy(
            device: device,
            testHostPath: configuration.testHostPath,
            testBundlePath: configuration.testBundlePath,
            withTimeout: configuration.timeout
          )**
So I added it to the commands line, (no state=booted):

 **f7ef872537597d1626df65185c6e4d9f95c4f546  launch_xctest /Users/jongabilondo/Library/Developer/Xcode/DerivedData/WebDriverAgent-czmwtfxwwepoqhgdtpnbqpovpwgf/Build/Products/Debug-iphoneos/IntegrationTests-Runner.app/PlugIns/IntegrationTests.xctest  /Users/jongabilondo/Library/Developer/Xcode/DerivedData/WebDriverAgent-czmwtfxwwepoqhgdtpnbqpovpwgf/Build/Products/Debug-iphoneos/IntegrationApp.app com.facebook.IntegrationApp  --port 8100 --listen**

Not it does get to a good point:
**- (FBTask *)runXCodeBuild
{
  NSMutableArray<NSString *> *arguments = [[NSMutableArray alloc] init];

  [arguments addObject: @"xcodebuild"];
  [arguments addObject: @"test-without-building"];
  [arguments addObject: @"-xctestrun"];
  [arguments addObject: self.filePath];
  [arguments addObject: @"-destination"];
  [arguments addObject: [NSString stringWithFormat:@"id=%@", self.device.udid]];**

The test app is launched .. but no tests are being executed on it ..

However I thought that it would not use "xcodebuild" to launch the test .. that it would bypass "xcodebuild" and communicate with the testManager using the private Xcode API is using ..

Does fbsimctl know to run the tests without "xcodebuild" ? 

Cheers.

**Comment by lawrencelomax** [comment]
> Is -state=booted necessary/correct for device

You don't need this argument if you are specifying a device UDID.

> However I thought that it would not use "xcodebuild" to launch the test .. that it would bypass "xcodebuild" and communicate with the testManager using the private Xcode API is using ..

Reversing Engineering the Private APIs that are used to bootstrap a test is not a goal for us, it's only been done in order that we can run tests on Multiple Simulators concurrently. This is because there is an internal limitation of the Xcode toolchain that means we couldn't use `xcodebuild` directly, the reason this is done for devices is there is no such limitation on launching tests on multiple devices from the same host.

I don't really have any objection to whichever method is used, it's more about what gets the job done. 

@wacban may also be able to help here. I wonder if there are some signing issues, or some other logs that we can get to explain the failure.

**Comment by JonGabilondoAngulo** [comment]
Hi, I understand, thanks.

Is the right command line this one then ?

fbsimctl device_uidid launch_xctest path_to_xctest path_to_app -port 8100 --listen 

thanks

**Comment by lawrencelomax** [comment]
> The second argument for devices needs to be the actual app instead of bundle id and it should be WDARunner app

Yes this is different between Simulators and Devices.

On a Simulator, we can inject a *signed* Test Bundle into an arbitrary application (Such as the iOS Settings App), which means we don't have to build an `WebDriverAgentRunner` app for Simulators in order to start `WebDriverAgent`.

This is not true of devices, which require that the Test Bundle be signed and run inside an Application that has the same signature. The process of doing this is also slightly different, as the test bundle is embedded as a Framework inside the Application Bundle and the whole package is signed together. When the Application launches, so does the Test Bundle.
