### ISSUE TITLE
Start WDA on device use fbsimctl

### ISSUE THREAD

**Issue by chsasaw** [facebook/FBSimulatorControl#345]
I use 
`fbsimctl $device_id --state=booted launch_xctest ~/....../WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest com.apple.mobilesafari --port 8100 -- listen`

the device shows nothing, and the log in terminal is short
`Listen Started: empty`

Am I using the wrong way?Can I just launch WDA and do nothing using fbsimctl with xctest file?

**Comment by wacban** [comment]
The second argument for devices needs to be the actual app instead of bundle id and it should be WDARunner app. No need for --state-booted. I haven't tested it with listen yet.

Can you try that:
fbsimctl $device_id launch_xctest ~/....../WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest ~/....../WebDriverAgentRunner-Runner.app

It will be launched inside WebDriverAgentRunner app.

**Comment by chsasaw** [comment]
@wacban 
Thank you very much! It works!
