### ISSUE TITLE
Unable to run tests without a host application

### ISSUE THREAD

**Issue by Asimk21** [facebook/FBSimulatorControl#411]
I am using fbsimctl via [pxctest](https://github.com/plu/pxctest) which I believe uses fbsimctl as the underlying mechanism for executing UI and none UI unit tests (the `xctest` files exist as plugins within the `Project.app` bundle.)

There appears currently to be no way to execute an `xctest` bundle directly, which is the resultant artifact of building a XCTest target that is not hosted within an application. 

Is this functionality going to be added to `fbsimctl` or am I missing something?

Any advice or suggestions is greatly appreciated! Thanks a lot.

**Comment by plu** [comment]
> using fbsimctl via pxctest which I believe uses fbsimctl as the underlying mechanism 

pxctest uses FBSimulatorControl, but not fbsimctl.

However if you want to see this feature in pxctest, you should probably open an issue there.

**Comment by ChrisAJS** [comment]
@plu thanks for the clarification, feel free to close this issue.

**Comment by lawrencelomax** [comment]
There is framework-level support for running "Logic Tests" (i.e. [tests that run in the `xctest` command line rather than a hosted `.app`](https://github.com/facebook/FBSimulatorControl/blob/master/fbxctest/Documentation/Details.md#logic-tests)) in `fbxctest`. This is not currently part of `FBSimulatorControl`, however it probably should be hoisted to `XCTestBootstrap` at some point in the future.

You will find support for running Application Tests in `FBSimulatorControl`, just not logic tests.
