### ISSUE TITLE
class x is implemented in both /usr/local/Cellar/... and /Applications/Xcode.app/...

### ISSUE THREAD

**Issue by vathsalahn** [facebook/FBSimulatorControl#412]
xcodebuild -version
Xcode 8.3.2
Build version 8E2002

» fbsimctl list

Class _TtCs18_EmptyArrayStorage is implemented in both /usr/local/Cellar/fbsimctl/HEAD-4b51af2/Frameworks/FBSimulatorControlKit.framework/Versions/A/Frameworks/libswiftCore.dylib (0x105f58990) and /Applications/Xcode.app/Contents/Frameworks/libswiftCore.dylib (0x108eed990). One of the two will be used. Which one is undefined.

**Comment by iMinder** [comment]
same problem here

**Comment by vathsalahn** [comment]
Can someone please help me out on this .

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen
