### ISSUE TITLE
launch_xctest on multiple simulators got UNEXPECTED QUIT error

### ISSUE THREAD

**Issue by zhangjin135** [facebook/FBSimulatorControl#417]
Hi Team,

I'm using fbsimctl and WebDriverAgent in XCode8.3.3 to run test cases on multiple simulators.
The command:

`fbsimctl  <uuid> launch_xctest PATH/TO/WDA/WebDriverAgentRunner.xctest com.apple.Preferences --port 8100 -- listen`

`fbsimctl  <uuid> launch_xctest PATH/TO/WDA/WebDriverAgentRunner.xctest com.apple.Preferences --port 8110 -- listen`

The simulators launches correctly, and the Preferences app launches, then I got an error **Preferences quit unexpectedly**. The simulator will show the Preferences view until I close it. EACHTIME!!!
This gonna drive me crazy. Any response could be appreciate.

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen
