### ISSUE TITLE
Add ability to take a screenshot

### ISSUE THREAD

**Issue by dhennessy** [facebook/FBSimulatorControl#46]
Is it possible to take a screenshot of the simulated app?  I see that DVDDevice.h has a method called:

```
- (void)takeScreenshotWithCompletionBlock:(CDUnknownBlockType)arg1;
```

It's not clear to me how I could access this object from FBSimulatorSessionInteraction.

**Comment by lawrencelomax** [comment]
Screenshots should certainly be possible one way or another:
1) Been thinking about interactions generalised to return 'id'. This could make more sense for some people rather than shoving the interesting information in the session state.
2) if it's not possible to use DVTDevice, we could screen capture the simulator app (yuck)
3) It should be possible to run a daemon process on the simulator that has access to the framebuffer (IIRC WebDriverAgent does this)

cc @mmmulani

**Comment by lawrencelomax** [comment]
This should be complete when I:
1) Fix the [callsite `FBWritableLog`](https://github.com/facebook/FBSimulatorControl/blob/master/FBSimulatorControl/Logs/FBSimulatorLogs.m#L114)
2) Add On-Demand fetching to `FBSimulatorFramebuffer` so that the latest image will always be used in preference to the cached value.

**Comment by lawrencelomax** [comment]
This exists in `FBSimulatorDiagnostics`
