### ISSUE TITLE
"No external dependencies." false

### ISSUE THREAD

**Issue by colinator** [facebook/FBSimulatorControl#461]
It depends on carthage, GCDWebServer, and homebrew.

And please make a pod installer! Homebrew is soo brittle.

**Comment by zeyadsalloum** [comment]
We just released idb. a new tool that improves significantly over fbsimctl. We recommend switching over. As part of our renewed commitment to this repo we are cleaning up old issues and will be monitoring and reviewing more closely from now on. if you still think this issue is relevant feel free to reopen

**Comment by lawrencelomax** [comment]
> It depends on carthage, GCDWebServer, and homebrew.

`FBSimulatorControl` doesn't depend on any of these, this is/was in the `README` for `FBSimulatorControl` not for any of the other projects. You can still use `FBSimulatorControl` as a vanilla Framework, without any dependencies

`fbsimctl` on the other hand does not, as do a handful of the tests.
